### ISSUE TITLE
Failing test cases with latest ImageMagick 6

### ISSUE THREAD

**Issue by mooninite** [rmagick/rmagick#1224]
### Description
ImageMagick 6 updates are always a mine field when it comes to the test cases provided by this project. Since ImageMagick is constantly bug fixing or security fixing expected output is always a moving target. Sometimes their fixes introduce new bugs. I do not know what is the cause as I am not familiar with this project so I have to open this issue.

### System Configuration

- ImageMagick version: 6.9.11.22
- RMagick version: 4.1.2
- Ruby version: 2.7.1
- Environment (Operating system, version and so on): Fedora 33 (Rawhide)
- Additional information:

```
export RUBYLIB=/builddir/build/BUILD/rmagick-4.1.2:/builddir/build/BUILD/rmagick-4.1.2/lib:/builddir/build/BUILD/rmagick-4.1.2/test:/builddir/build/BUILDROOT/rubygem-rmagick-4.1.2-3.fc33.x86_64/usr/lib64/gems/ruby/rmagick-4.1.2
RUBYLIB=/builddir/build/BUILD/rmagick-4.1.2:/builddir/build/BUILD/rmagick-4.1.2/lib:/builddir/build/BUILD/rmagick-4.1.2/test:/builddir/build/BUILDROOT/rubygem-rmagick-4.1.2-3.fc33.x86_64/usr/lib64/gems/ruby/rmagick-4.1.2
export COVERAGE=false
COVERAGE=false
rspec spec/
.......................................F.............................................................................................................................................................*.............................................................................................................................................................................................*......................................................**.............................................................................................................................................................................................................
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Magick::Image#changed? works
     # image is initially changed
     # ./spec/rmagick/image/changed_predicate_spec.rb:2

  2) Magick::Image#liquid_rescale works
     # delegate library support not built-in ''
     # ./spec/rmagick/image/liquid_rescale_spec.rb:2

  3) Magick::Image#read issue #200 not hangs with nil argument
     # No reason given
     # ./spec/rmagick/image/read_spec.rb:17

  4) Magick::Image#read issue #200 raise error with nil argument
     # No reason given
     # ./spec/rmagick/image/read_spec.rb:22

Failures:
  1) Magick::Draw#clip_path works
     Failure/Error: draw.draw(canvas)
     
     Magick::ImageMagickError:
       unable to open image `7': No such file or directory @ error/blob.c/OpenBlob/2926
     # ./spec/rmagick/draw/clip_path_spec.rb:29:in `draw'
     # ./spec/rmagick/draw/clip_path_spec.rb:29:in `block (2 levels) in <top (required)>'
Finished in 20.92 seconds (files took 0.44348 seconds to load)
649 examples, 1 failure, 4 pending
Failed examples:
rspec ./spec/rmagick/draw/clip_path_spec.rb:11 # Magick::Draw#clip_path works
```

**Comment by dlemstra** [comment]
This issue has been resoled with the following commit: https://github.com/ImageMagick/ImageMagick/commit/da464ac96e7f1ae63bd2cfb2f143f2fc87214fe1

**Comment by Watson1978** [comment]
If you use ImageMagick 6.9.11.23, the problem should be resolved

Refer : https://github.com/rmagick/rmagick/pull/1222
