### ISSUE TITLE
 LoadError:dlopen(/Library/Ruby/Gems/2.6.0/gems/rmagick-4.1.2/lib/RMagick2.bundle, 0x0009)

### ISSUE THREAD

**Issue by puyangdev** [rmagick/rmagick#1247]
```
LoadError: dlopen(/Library/Ruby/Gems/2.6.0/gems/rmagick-4.1.2/lib/RMagick2.bundle, 0x0009): dependent dylib '/usr/local/opt/freetype/lib/libfreetype.6.dylib' not found for '/usr/local/Cellar/imagemagick/7.0.10-0/lib/libMagickCore-7.Q16HDRI.7.dylib' - /Library/Ruby/Gems/2.6.0/gems/rmagick-4.1.2/lib/RMagick2.bundle
  /Library/Ruby/Gems/2.6.0/gems/rmagick-4.1.2/lib/rmagick_internal.rb:23:in `require'
  /Library/Ruby/Gems/2.6.0/gems/rmagick-4.1.2/lib/rmagick_internal.rb:23:in `<top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/rmagick-4.1.2/lib/RMagick.rb:1:in `require'
  /Library/Ruby/Gems/2.6.0/gems/rmagick-4.1.2/lib/RMagick.rb:1:in `<top (required)>'
  Fastfile:22:in `require'
  Fastfile:22:in `parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in p
```

**Comment by mockdeep** [comment]
@puyangdev it looks like you might be using an out of date version of ImageMagick. Can you upgrade to `7.0.10-34` or later? It also looks like you may not have freetype installed, which you should be able to handle with `brew install freetype`. You may also want to do `brew update` and `brew doctor` to make sure your homebrew is in good shape.

**Comment by Watson1978** [comment]
Through `brew install freetype`, this problem will be solved.
Feel free to reopen this issue, if you still have this problem.
