### ISSUE TITLE
rmagick requires libMagickCore-7

### ISSUE THREAD

**Issue by MrJadaml** [rmagick/rmagick#1293]
### Description

Failing to find dependency `libMagickCore-7.Q16HDRI.so.10` when running a rails server for the first time.

```
 /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/rmagick_internal.rb:23:in `require': libMagickCore-7.Q16HDRI.so.10: cannot open shared object file: No such file or directory - /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/RMagick2.so (LoadError)

15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/rmagick_internal.rb:23:in `<top (required)>'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/rmagick.rb:1:in `require'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/rmagick.rb:1:in `<top (required)>'
15:32:12 worker.1 | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
15:32:12 worker.1 | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
15:32:12 worker.1 | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
15:32:12 worker.1 | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
15:32:12 worker.1 | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
15:32:12 worker.1 | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
15:32:12 worker.1 | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
15:32:12 worker.1 | 	from /home/foo/garmentier/garmentier/config/application.rb:9:in `<top (required)>'
15:32:12 worker.1 | 	from /home/foo/garmentier/garmentier/config/environment.rb:2:in `require_relative'
15:32:12 worker.1 | 	from /home/foo/garmentier/garmentier/config/environment.rb:2:in `<top (required)>'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:252:in `require'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:252:in `boot_system'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:37:in `run'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/sidekiq-6.0.7/bin/sidekiq:31:in `<top (required)>'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/bin/sidekiq:23:in `load'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/bin/sidekiq:23:in `<main>'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/bin/ruby_executable_hooks:22:in `eval'
15:32:12 worker.1 | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/bin/ruby_executable_hooks:22:in `<main>'

15:32:12 web.1    | /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/rmagick_internal.rb:23:in `require': libMagickCore-7.Q16HDRI.so.10: cannot open shared object file: No such file or directory - /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/RMagick2.so (LoadError)

15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/rmagick_internal.rb:23:in `<top (required)>'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/rmagick.rb:1:in `require'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/rmagick-4.2.2/lib/rmagick.rb:1:in `<top (required)>'
15:32:12 web.1    | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
15:32:12 web.1    | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
15:32:12 web.1    | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
15:32:12 web.1    | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
15:32:12 web.1    | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
15:32:12 web.1    | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
15:32:12 web.1    | 	from /home/foo/.rvm/rubies/ruby-2.5.8/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
15:32:12 web.1    | 	from /home/foo/garmentier/garmentier/config/application.rb:9:in `<top (required)>'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:145:in `require'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:145:in `block in perform'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `tap'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `perform'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
15:32:12 web.1    | 	from /home/foo/garmentier/garmentier/bin/rails:9:in `require'
15:32:12 web.1    | 	from /home/foo/garmentier/garmentier/bin/rails:9:in `<top (required)>'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
15:32:12 web.1    | 	from /home/foo/.rvm/gems/ruby-2.5.8@curate/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
15:32:12 web.1    | 	from /home/foo/garmentier/garmentier/bin/spring:15:in `require'
15:32:12 web.1    | 	from /home/foo/garmentier/garmentier/bin/spring:15:in `<top (required)>'
15:32:12 web.1    | 	from bin/rails:3:in `load'
15:32:12 web.1    | 	from bin/rails:3:in `<main>'
15:32:12 web.1    | exited with code 1
15:32:12 system   | sending SIGTERM to all processes
15:32:12 worker.1 | exited with code 1
15:32:12 assets.1 | terminated by SIGTERM
```

### Steps to Reproduce

```
brew install imagemagick
gem install rmagick -v '4.2.2'
bundle install
rails s
```

### System Configuration

- ImageMagick version: **7.1.0-5**
- RMagick version: tried **4.1.2** and **4.2.2**
- Ruby version: **2.5.8p224**
- Environment (Operating system, version and so on): **Linux - PopOS 21.04**
- Additional information:
installed these: `sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev`
tried searching `apt` package manager for `libmagickcore` but only variants of v6 show up. No v7 options.

**Comment by Watson1978** [comment]
The path to the ImageMagick library might have changed.

Could you please reinstall `rmagick` ?

```
$ gem pristine rmagick
```

**Comment by Watson1978** [comment]
Through `gem pristine rmagick`, this problem will be solved.
Feel free to reopen this issue, if you still have this problem.
