### ISSUE TITLE
Segfault occurs as soon as requires sorted_set or rbtree

### ISSUE THREAD

**Issue by kimyu92** [rmagick/rmagick#1334]
### Description

As soon as, I installed both `rmagick` and `rbtree` or `rmagick` with `sorted_set`, segmentation fault would happen immediately with the single file rails setup below.

```
-- Control frame information -----------------------------------------------
c:0066 p:---- s:0334 e:000333 CFUNC  :read
c:0065 p:0050 s:0329 e:000328 METHOD /usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/processing/rmagick.rb:352
c:0064 p:0018 s:0317 e:000316 METHOD /usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/processing/rmagick.rb:176
c:0063 p:0050 s:0311 e:000310 BLOCK  /usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/processing.rb:83 [FINISH]
c:0062 p:---- s:0305 e:000304 CFUNC  :each
c:0061 p:0009 s:0301 e:000300 BLOCK  /usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/processing.rb:75
c:0060 p:0016 s:0298 e:000297 METHOD /usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/callbacks.rb:15
c:0059 p:0018 s:0292 e:000291 METHOD /usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/processing.rb:74
c:0058 p:0010 s:0287 e:000286 BLOCK  /usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/callbacks.rb:14 [FINISH]
c:0057 p:---- s:0283 e:000282 CFUNC  :each

...

-- Ruby level backtrace information ----------------------------------------
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:24:in `block in autorun'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:38:in `perform_at_exit'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:89:in `run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:115:in `run_specs'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:74:in `report'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2068:in `with_suite_hooks'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `map'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:607:in `run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `run_examples'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `map'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:259:in `run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
/usr/local/bundle/gems/rspec-rails-5.1.2/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `block in run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:261:in `block in run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:505:in `run_before_example'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:484:in `run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:614:in `reverse_each'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:528:in `each'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:365:in `run'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
/usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
repro.rb:69:in `block (2 levels) in <main>'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/orm/activerecord.rb:75:in `avatar='
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/mount.rb:373:in `avatar='
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/mount.rb:146:in `avatar='
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:46:in `cache'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:46:in `map'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:47:in `block in cache'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:176:in `handle_error'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:63:in `block (2 levels) in cache'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/cache.rb:144:in `cache!'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/callbacks.rb:14:in `with_callbacks'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/callbacks.rb:14:in `each'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/processing.rb:74:in `process!'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/processing.rb:75:in `block in process!'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/processing.rb:75:in `each'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/uploader/processing.rb:83:in `block (2 levels) in process!'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/processing/rmagick.rb:176:in `resize_to_fit'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/processing/rmagick.rb:352:in `manipulate!'
/usr/local/bundle/gems/carrierwave-2.2.2/lib/carrierwave/processing/rmagick.rb:352:in `read'
```

### Steps to Reproduce

1. Pull either `docker pull ruby:2.7.6-alpine3.15` or `docker pull ruby:3.0.4-alpine3.15` or `docker pull ruby:3.1.2-alpine3.15`
1. Save this file as `repro.rb` in container
1. Run command to install imagemagick 7, `apk add pkgconfig imagemagick imagemagick-dev imagemagick-libs`
1. Run command to install sqlite3 `apk add sqlite sqlite-dev`
1. Run command to install other sys libs `apk add build-base gcc autoconf libffi-dev openssl-dev`
1. Run `ruby repro.rb` inside docker container
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', '~> 7.0.2.3'
  gem 'rspec-rails', '~> 5.1.1'

  gem 'carrierwave'
  gem 'rmagick', '~> 4.2.5'

  # either gem would make interpreter blows up
  # adding , require: false on either gem would make it work but not ideal
  # gem 'rbtree'
  gem 'sorted_set'
  gem 'sqlite3'
end

require 'rmagick'

require 'active_support'
require 'active_support/core_ext/object/blank'
require 'active_record'

require 'action_controller/railtie'
require 'action_view/railtie'

require 'rspec/autorun'
require 'rspec/rails'
require 'carrierwave/orm/activerecord'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  drop_table :users, if_exists: true

  create_table :users, force: true do |t|
    t.timestamps null: false
    t.string :avatar
  end
end

class AvatarUploader < CarrierWave::Uploader::Base
  include CarrierWave::RMagick
  storage :file

  process resize_to_fit: [777, 777]
end

class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

RSpec.configure do |config|
  config.filter_run_excluding skip: true
  config.run_all_when_everything_filtered = true
  config.filter_run focus: true
end

RSpec.describe 'Segfault error' do
  let(:user) { User.new }
  let(:file) { Tempfile.new }
  let(:avatar) { Rack::Test::UploadedFile.new(file, 'application/pdf', true, original_filename: 'sample.pdf') }
  let(:avatar_key) { sample_key(User.new.uploader, extension: 'pdf') }

  before do
    user.avatar = avatar
  end

  it { expect(user.avatar).to eq(avatar) }
end
```

### System Configuration

- ImageMagick version: 7.1.0-16 Q16-HDRI x86_64
- RMagick version: 4.2.5
- Ruby version: 2.7.6/3.0.4/3.1.2
- Environment (Operating system, version and so on): alpine 3.15.x (official ruby image in docker hub, https://hub.docker.com/_/ruby?tab=tags)
- Additional information:

**Comment by kimyu92** [comment]
@Watson1978 please let me know if you have any insight especially this is most likely involve C extension 🤷

**Comment by Watson1978** [comment]
If possible, it would be better to use something other than PDF, since processing JPEG instead of PDF does not seem to cause SEGV.

**Comment by kimyu92** [comment]
> hmm, I confirmed that your code causes SEGV within rbtree.
> I will investigate this deeply at weekend

Thank you

> I don't know why it calls rbtree

💯 Shouldn't `rmagick` and `rbtree` be isolated unless c extension clashed with each other via `include`? 😅

**Comment by Watson1978** [comment]
A simpler reproduction code would look like below.

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rmagick', '~> 4.2.5'
  gem 'sorted_set'
end

require 'rmagick'
require 'sorted_set'

image Magick::Image.read('sample.pdf')
```

**Comment by Watson1978** [comment]
I'm guessing there is something wrong with the alpine configuration or something, and the loaded C symbols are conflicting....

**Comment by kimyu92** [comment]
> I'm guessing there is something wrong with the alpine configuration or something, and the loaded C symbols are conflicting....

I'm curious would it be due to [dict_first() from ghostscript](http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=8ac0975771838c7d8c17f5f2f7223607eb976788) vs [dict_first() defined by rbtree](https://github.com/kyrylo/rbtree3/blob/850e9d76c22b0766bc2bc36987b11aed05eb2bb4/dict.h#L95-L96)

**Comment by Watson1978** [comment]
At least, there is no way that can be solved with RMagick.

**Comment by kimyu92** [comment]
@Watson1978 I highly appreciated the gist above and I agreed with you that this is not related to rmagick. `musl` is usually stricter than `glibc`, I still lean towards the issue might come from `rbtree` because without including it, the rmagick works fine.

**Comment by Watson1978** [comment]
I think the rbtree and ghostscript libraries are not linked, so it is curious that the symbols conflict.
And because your reproduction code works on ubuntu image.
