### ISSUE TITLE
Rmagick 5.1 fails to run, fine with 5.0

### ISSUE THREAD

**Issue by travisbell** [rmagick/rmagick#1369]
### Description

Hi guys,

Not sure what's going on but when I try to start my app with 5.1, Bundler is failing with the following error:

```
Ruby: /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:63:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'rmagick'.

Gem Load Error is: This installation of RMagick was configured with ImageMagick 6.9.10 but ImageMagick 6.9.12-19 is in use.
Please re-install RMagick to correct the issue.

Backtrace for gem load error is:

/usr/local/bundle/gems/rmagick-5.1.0/lib/rmagick_internal.rb:25:in `require'
/usr/local/bundle/gems/rmagick-5.1.0/lib/rmagick_internal.rb:25:in `<top (required)>'
/usr/local/bundle/gems/rmagick-5.1.0/lib/rmagick.rb:3:in `require'
/usr/local/bundle/gems/rmagick-5.1.0/lib/rmagick.rb:3:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:60:in `require'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `each'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:55:in `block in require'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `each'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler/runtime.rb:44:in `require'
/usr/local/bundle/gems/bundler-2.3.19/lib/bundler.rb:188:in `require'
config.ru:5:in `block in <main>'
```

The weird thing is, I don't have ImageMagick 6.9.10 installed (nor have I ever):

```bash
$ identify -version
Version: ImageMagick 6.9.12-19 Q16 x86_64 2021-07-18 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr png rsvg tiff webp wmf x xml zlib

$ Magick-config --version
6.9.12-19 Q16
```

This is on Ubuntu 20.04 and Ruby 3.1.2.

If I downgrade to rmagick 5.0, everything works as expected. I also tried uninstalling rmagick, but re-installing it yields the same error.

Thanks!

**Comment by mockdeep** [comment]
Thanks for reporting! @Watson1978 is this a problem with the new pkg-config gem?

**Comment by Watson1978** [comment]
@travisbell Could you attach the log of installing RMagick ?

The easiest way is to uninstall the unused ImageMagick 6.9.10.

**Comment by Watson1978** [comment]
> is this a problem with the new pkg-config gem?

It would seem so.

**Comment by travisbell** [comment]
@Watson1978 Thanks!

I took a look and indeed, it looks like `libmagickwand-dev` was installed on this instance. But before I go mess with that, here's the two install logs, so you can see how 5.0 and 5.1 are different.

### 5.0

```
gem install rmagick -v 5.0 --verbose
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/rmagick
200 OK
GET https://index.rubygems.org/quick/Marshal.4.8/rmagick-5.0.0.gemspec.rz
200 OK
Downloading gem rmagick-5.0.0.gem
GET https://index.rubygems.org/gems/rmagick-5.0.0.gem
Fetching rmagick-5.0.0.gem
200 OK
/usr/local/bundle/gems/rmagick-5.0.0/.codeclimate.yml
/usr/local/bundle/gems/rmagick-5.0.0/.devcontainer/Dockerfile
/usr/local/bundle/gems/rmagick-5.0.0/.devcontainer/ImageMagick6/devcontainer.json
/usr/local/bundle/gems/rmagick-5.0.0/.devcontainer/devcontainer.json
/usr/local/bundle/gems/rmagick-5.0.0/.devcontainer/setup-repo.sh
/usr/local/bundle/gems/rmagick-5.0.0/.devcontainer/setup-user.sh
/usr/local/bundle/gems/rmagick-5.0.0/.editorconfig
/usr/local/bundle/gems/rmagick-5.0.0/.github/ISSUE_TEMPLATE.md
/usr/local/bundle/gems/rmagick-5.0.0/.github/workflows/ci.yml
/usr/local/bundle/gems/rmagick-5.0.0/.gitignore
/usr/local/bundle/gems/rmagick-5.0.0/.rspec
/usr/local/bundle/gems/rmagick-5.0.0/.rubocop.yml
/usr/local/bundle/gems/rmagick-5.0.0/.rubocop_todo.yml
/usr/local/bundle/gems/rmagick-5.0.0/.yardopts
/usr/local/bundle/gems/rmagick-5.0.0/CHANGELOG.md
/usr/local/bundle/gems/rmagick-5.0.0/CODE_OF_CONDUCT.md
/usr/local/bundle/gems/rmagick-5.0.0/CONTRIBUTING.md
/usr/local/bundle/gems/rmagick-5.0.0/Gemfile
/usr/local/bundle/gems/rmagick-5.0.0/LICENSE
/usr/local/bundle/gems/rmagick-5.0.0/README.md
/usr/local/bundle/gems/rmagick-5.0.0/Rakefile
/usr/local/bundle/gems/rmagick-5.0.0/before_install_linux.sh
/usr/local/bundle/gems/rmagick-5.0.0/before_install_osx.sh
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/extconf.rb
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmagick.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmagick.h
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmdraw.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmenum.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmfill.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmilist.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmimage.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rminfo.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmkinfo.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmmain.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmmontage.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmpixel.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmstruct.c
/usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick/rmutil.c
/usr/local/bundle/gems/rmagick-5.0.0/lib/rmagick.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rmagick/version.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rmagick_internal.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/clippath.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/container.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/deep_equal.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/describable.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/embellishable.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/misc.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/paint.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/pathdata.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/rvg.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/stretchable.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/stylable.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/text.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/transformable.rb
/usr/local/bundle/gems/rmagick-5.0.0/lib/rvg/units.rb
/usr/local/bundle/gems/rmagick-5.0.0/rmagick.gemspec
Building native extensions. This could take a while...
current directory: /usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick
["/usr/local/bin/ruby", "-I", "/usr/local/lib/ruby/3.1.0", "-r", "./siteconf20221117-1723-qruiah.rb", "extconf.rb"]
checking for brew... no
checking for pacman... no
checking for Ruby version >= 2.3.0... yes
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for gcc... yes

Warning: Found a partial ImageMagick installation. Your operating
system likely has some built-in ImageMagick libraries but not all of
ImageMagick. This will most likely cause problems at both compile and
runtime.
Found partial installation at: /usr/local

checking for __GNUC__... yes
checking for MagickCore/MagickCore.h... no
checking for magick/MagickCore.h... yes
checking for rb_gc_adjust_memory_usage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for posix_memalign() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for malloc_usable_size() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for malloc_size() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... no
checking for _aligned_msize() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... no
checking for GetImageChannelEntropy() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for SetImageGray() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for SetMagickAlignedMemoryMethods() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for malloc.h... yes
creating extconf.h
creating Makefile
======================================================================
Thu 17 Nov 22 16:16:59
This installation of RMagick 5.0.0 is configured for
Ruby 3.1.2 (x86_64-linux) and ImageMagick 6.9.12
======================================================================


Configured compile options: {:magick_version=>"6.9.12", :local_libs=>" -L/usr/local/lib -lMagickCore-6.Q16", :cppflags=>" -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/include/ImageMagick-6 -std=gnu99", :ldflags=>" -L/usr/local/lib -lMagickCore-6.Q16 -Wl,-rpath,/usr/local/lib", :defs=>[], :config_h=>"Makefile"}
current directory: /usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick
["make", "DESTDIR=", "clean"]

current directory: /usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick
["make", "DESTDIR="]
compiling rmagick.c
compiling rmdraw.c
compiling rmenum.c
compiling rmfill.c
compiling rmilist.c
compiling rmimage.c
compiling rminfo.c
compiling rmkinfo.c
compiling rmmain.c
compiling rmmontage.c
compiling rmpixel.c
compiling rmstruct.c
compiling rmutil.c
linking shared-object RMagick2.so
current directory: /usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick
["make", "DESTDIR=", "install"]
/usr/bin/install -c -m 0755 RMagick2.so ./.gem.20221117-1723-czjta1
current directory: /usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20221117-1723-qruiah.rb extconf.rb
current directory: /usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick
make DESTDIR\= clean
current directory: /usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick
make DESTDIR\=
current directory: /usr/local/bundle/gems/rmagick-5.0.0/ext/RMagick
make DESTDIR\= install
Successfully installed rmagick-5.0.0
Parsing documentation for rmagick-5.0.0
Parsing sources...
100% [49/49]  lib/rvg/units.rb
Installing ri documentation for rmagick-5.0.0
Done installing documentation for rmagick after 4 seconds
1 gem installed
```

### 5.1

```
gem install rmagick --verbose
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/rmagick
200 OK
GET https://index.rubygems.org/quick/Marshal.4.8/rmagick-5.1.0.gemspec.rz
200 OK
GET https://index.rubygems.org/info/pkg-config
200 OK
Downloading gem rmagick-5.1.0.gem
GET https://index.rubygems.org/gems/rmagick-5.1.0.gem
Fetching rmagick-5.1.0.gem
200 OK
/usr/local/bundle/gems/rmagick-5.1.0/.codeclimate.yml
/usr/local/bundle/gems/rmagick-5.1.0/.devcontainer/Dockerfile
/usr/local/bundle/gems/rmagick-5.1.0/.devcontainer/ImageMagick6/devcontainer.json
/usr/local/bundle/gems/rmagick-5.1.0/.devcontainer/devcontainer.json
/usr/local/bundle/gems/rmagick-5.1.0/.devcontainer/setup-repo.sh
/usr/local/bundle/gems/rmagick-5.1.0/.devcontainer/setup-user.sh
/usr/local/bundle/gems/rmagick-5.1.0/.editorconfig
/usr/local/bundle/gems/rmagick-5.1.0/.github/ISSUE_TEMPLATE.md
/usr/local/bundle/gems/rmagick-5.1.0/.github/workflows/ci.yml
/usr/local/bundle/gems/rmagick-5.1.0/.gitignore
/usr/local/bundle/gems/rmagick-5.1.0/.rspec
/usr/local/bundle/gems/rmagick-5.1.0/.rubocop.yml
/usr/local/bundle/gems/rmagick-5.1.0/.rubocop_todo.yml
/usr/local/bundle/gems/rmagick-5.1.0/.yardopts
/usr/local/bundle/gems/rmagick-5.1.0/CHANGELOG.md
/usr/local/bundle/gems/rmagick-5.1.0/CODE_OF_CONDUCT.md
/usr/local/bundle/gems/rmagick-5.1.0/CONTRIBUTING.md
/usr/local/bundle/gems/rmagick-5.1.0/Gemfile
/usr/local/bundle/gems/rmagick-5.1.0/LICENSE
/usr/local/bundle/gems/rmagick-5.1.0/README.md
/usr/local/bundle/gems/rmagick-5.1.0/Rakefile
/usr/local/bundle/gems/rmagick-5.1.0/before_install_linux.sh
/usr/local/bundle/gems/rmagick-5.1.0/before_install_osx.sh
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/extconf.rb
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmagick.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmagick.h
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmagick_gvl.h
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmdraw.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmenum.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmfill.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmilist.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmimage.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rminfo.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmkinfo.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmmain.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmmontage.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmpixel.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmstruct.c
/usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick/rmutil.c
/usr/local/bundle/gems/rmagick-5.1.0/lib/rmagick.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rmagick/version.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rmagick_internal.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/clippath.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/container.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/deep_equal.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/describable.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/embellishable.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/misc.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/paint.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/pathdata.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/rvg.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/stretchable.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/stylable.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/text.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/transformable.rb
/usr/local/bundle/gems/rmagick-5.1.0/lib/rvg/units.rb
/usr/local/bundle/gems/rmagick-5.1.0/rmagick.gemspec
Building native extensions. This could take a while...
current directory: /usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick
["/usr/local/bin/ruby", "-I", "/usr/local/lib/ruby/3.1.0", "-r", "./siteconf20221117-1572-gq6mxz.rb", "extconf.rb"]
checking for brew... no
checking for pacman... no
checking for Ruby version >= 2.3.0... yes
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for gcc... yes

Warning: Found a partial ImageMagick installation. Your operating
system likely has some built-in ImageMagick libraries but not all of
ImageMagick. This will most likely cause problems at both compile and
runtime.
Found partial installation at: /usr/local

checking for __GNUC__... yes
checking for MagickCore/MagickCore.h... no
checking for magick/MagickCore.h... yes
checking for rb_gc_adjust_memory_usage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for posix_memalign() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for malloc_usable_size() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for malloc_size() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... no
checking for _aligned_msize() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... no
checking for GetImageChannelEntropy() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for SetImageGray() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for SetMagickAlignedMemoryMethods() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for malloc.h... yes
creating extconf.h
creating Makefile
======================================================================
Thu 17 Nov 22 03:48:55
This installation of RMagick 5.1.0 is configured for
Ruby 3.1.2 (x86_64-linux) and ImageMagick 6.9.10
======================================================================


Configured compile options: {:magick_version=>"6.9.10", :local_libs=>"  -L/usr/lib/x86_64-linux-gnu -lMagickCore-6.Q16", :cppflags=>"-I/usr/local/include  $(DEFS) $(cppflags)  -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -std=gnu99 -Wno-void-pointer-to-int-cast -Wno-void-pointer-to-enum-cast -Wno-pointer-to-int-cast", :ldflags=>"-L. -L/usr/local/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed  -L/usr/lib/x86_64-linux-gnu -lMagickCore-6.Q16 -Wl,-rpath,/usr/lib/x86_64-linux-gnu", :defs=>["-DHAVE_MAGICK_MAGICKCORE_H", "-DHAVE_RB_GC_ADJUST_MEMORY_USAGE", "-DHAVE_POSIX_MEMALIGN", "-DHAVE_MALLOC_USABLE_SIZE", "-DHAVE_GETIMAGECHANNELENTROPY", "-DHAVE_SETIMAGEGRAY", "-DHAVE_SETMAGICKALIGNEDMEMORYMETHODS", "-DHAVE_MALLOC_H", "-DRUBY_VERSION_STRING=\"ruby 3.1.2\"", "-DRMAGICK_VERSION_STRING=\"RMagick 5.1.0\"", "-DIMAGEMAGICK_GREATER_THAN_EQUAL_6_8_9=1", "-DIMAGEMAGICK_GREATER_THAN_EQUAL_6_9_0=1", "-DIMAGEMAGICK_GREATER_THAN_EQUAL_6_9_10=1"], :config_h=>"Makefile"}
current directory: /usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick
["make", "DESTDIR=", "clean"]

current directory: /usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick
["make", "DESTDIR="]
compiling rmagick.c
compiling rmdraw.c
compiling rmenum.c
compiling rmfill.c
compiling rmilist.c
compiling rmimage.c
compiling rminfo.c
compiling rmkinfo.c
compiling rmmain.c
rmmain.c: In function ‘managed_memory_enable’:
rmmain.c:196:9: warning: implicit declaration of function ‘SetMagickAlignedMemoryMethods’; did you mean ‘SetMagickMemoryMethods’? [-Wimplicit-function-declaration]
  196 |         SetMagickAlignedMemoryMethods(rm_aligned_malloc, rm_aligned_free);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         SetMagickMemoryMethods
rmmain.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-void-pointer-to-enum-cast’
cc1: warning: unrecognized command line option ‘-Wno-void-pointer-to-int-cast’
compiling rmmontage.c
compiling rmpixel.c
compiling rmstruct.c
compiling rmutil.c
linking shared-object RMagick2.so
current directory: /usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick
["make", "DESTDIR=", "install"]
/usr/bin/install -c -m 0755 RMagick2.so ./.gem.20221117-1572-jluqc5
current directory: /usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20221117-1572-gq6mxz.rb extconf.rb
current directory: /usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick
make DESTDIR\= clean
current directory: /usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick
make DESTDIR\=
current directory: /usr/local/bundle/gems/rmagick-5.1.0/ext/RMagick
make DESTDIR\= install
Successfully installed rmagick-5.1.0
Parsing documentation for rmagick-5.1.0
Parsing sources...
100% [50/50]  lib/rvg/units.rb
Installing ri documentation for rmagick-5.1.0
Done installing documentation for rmagick after 1 seconds
1 gem installed
```

**Comment by Watson1978** [comment]
Hmm, I'm guessing that pkg-config gem have different  paths priorities.

If you specify `PKG_CONFIG_PATH`, it will use what you installed there

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```

**Comment by Watson1978** [comment]
Now, `pkg-config` gem has solved compatibility problem and your problem should be solved.
Thanks
