### ISSUE TITLE
rmagick 5.3.0 rspec testsuite fails with ImageMagick 7.1.1-26 (was okay with 7.1.1-15)

### ISSUE THREAD

**Issue by mtasaka** [rmagick/rmagick#1429]
With ImageMagick 7.1.1-26, rmagick 5.3.0 testsuite fails like:

```
Failures:

  1) Magick.limit_resources works
     Failure/Error: expect(cur > 300).to be(true)
     
       expected true
            got false
     # ./spec/rmagick/class_methods/limit_resources_spec.rb:35:in `block (2 levels) in <top (required)>'

  2) Magick::Image#gamma works
     Failure/Error: expect(image.gamma).to eq(0.45454543828964233)
     
       expected: 0.45454543828964233
            got: 0.45454545454545453
     
       (compared using ==)
     # ./spec/rmagick/image/gamma_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 41.3 seconds (files took 0.49459 seconds to load)
740 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/rmagick/class_methods/limit_resources_spec.rb:2 # Magick.limit_resources works
rspec ./spec/rmagick/image/gamma_spec.rb:2 # Magick::Image#gamma works
```

With ImageMagick 7.1.1-15, there are no test failures.

**Comment by mtasaka** [comment]
Looks like the first error will be resolved with https://github.com/rmagick/rmagick/commit/e7e5c9cc7f84759a5410e917cdb71cefb5cb0e92 .

Now 2nd error is left.
