### ISSUE TITLE
An error occurred while running bundle install or gem install rmagick -v '2.16.0'

### ISSUE THREAD

**Issue by yiningt-pp** [rmagick/rmagick#1430]
### Description
I saw post like [this][1] and tried advice there but problem still exists, and also reach out to [imagemagick](https://github.com/ImageMagick/ImageMagick/issues/7043) so posting here. Thanks in advance!

when I run `DEPENDENCIES_NEXT=0 bundle install` or `gem install rmagick -v '2.16.0'` I got following error:

```
Fetching gem metadata from https://gem.fury.io/yyyyyy/
Fetching gem metadata from https://gems.contribsys.com/
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Installing bootboot 0.1.2
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://gems.contribsys.com/..
Fetching gem metadata from https://gem.fury.io/yyyyyy/..
Installing rmagick 2.16.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/rmagick-2.16.0/ext/RMagick
/Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/bin/ruby -I /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0 -r ./siteconf20240118-37776-bfgumt.rb extconf.rb
--with-cflags\=-Wno-implicit-function-declaration
checking for gcc... yes
checking for Magick-config... yes

Warning: Found more than one ImageMagick installation. This could cause problems at runtime.
         /opt/homebrew/opt/imagemagick@6/bin/Magick-config reports version 6.9.13-4 Q16 is installed in /opt/homebrew/Cellar/imagemagick@6/6.9.13-4
         /opt/homebrew/bin/Magick-config reports version 6.9.13-4 Q16 is installed in /opt/homebrew/Cellar/imagemagick@6/6.9.13-4
Using 6.9.13-4 Q16 from /opt/homebrew/Cellar/imagemagick@6/6.9.13-4.

checking for outdated ImageMagick version (<= 6.4.9)... no
checking for presence of MagickWand API (ImageMagick version >= 6.9.0)... no
/opt/homebrew/opt/imagemagick@6/bin/MagickWand-config: line 63: unexpected EOF while looking for matching `"'
/opt/homebrew/opt/imagemagick@6/bin/MagickWand-config: line 70: syntax error: unexpected end of file
/opt/homebrew/opt/imagemagick@6/bin/MagickWand-config: line 63: unexpected EOF while looking for matching `"'
/opt/homebrew/opt/imagemagick@6/bin/MagickWand-config: line 70: syntax error: unexpected end of file
/opt/homebrew/opt/imagemagick@6/bin/MagickWand-config: line 63: unexpected EOF while looking for matching `"'
/opt/homebrew/opt/imagemagick@6/bin/MagickWand-config: line 70: syntax error: unexpected end of file
/opt/homebrew/opt/imagemagick@6/bin/MagickWand-config: line 63: unexpected EOF while looking for matching `"'
/opt/homebrew/opt/imagemagick@6/bin/MagickWand-config: line 70: syntax error: unexpected end of file
checking for Ruby version >= 1.8.5... yes
checking for stdint.h... yes
checking for sys/types.h... yes
checking for wand/MagickWand.h... no

Can't install RMagick 2.16.0. Can't find MagickWand.h.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/bin/$(RUBY_BASE_NAME)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/extensions/-darwin-22/2.6.0/rmagick-2.16.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/rmagick-2.16.0 for inspection.
Results logged to /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/extensions/-darwin-22/2.6.0/rmagick-2.16.0/gem_make.out

  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:90:in `run'
  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tempfile.rb:295:in `open'
  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:156:in `build_extension'
  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:190:in `block in build_extensions'
  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:187:in `each'
  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:187:in `build_extensions'
  /Users/xxxxxxxxx/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:821:in `build_extensions'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/rubygems_gem_installer.rb:76:in `build_extensions'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:203:in `install'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:130:in `do_install'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:121:in `block in worker_pool'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/worker.rb:62:in `apply_func'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `loop'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `process_queue'
  /Users/xxxxxxxxx/.rvm/gems/ruby-2.6.6@yyyyyy/gems/bundler-2.4.22/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing rmagick (2.16.0), and Bundler cannot continue.

In Gemfile:
  gruff was resolved to 0.7.0, which depends on
    rmagick
```

I tried reinstall and relink image, and those were executed successfully:

```
yyyyyyyyy@bcd074b3401b xxxxxx % brew unlink imagemagick@6
Unlinking /opt/homebrew/Cellar/imagemagick@6/6.9.13-4... 0 symlinks removed.
yyyyyyyyy@bcd074b3401b xxxxxx % brew link --force imagemagick@6

Linking /opt/homebrew/Cellar/imagemagick@6/6.9.13-4... 76 symlinks created.

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/opt/homebrew/opt/imagemagick@6/bin:$PATH"' >> ~/.zshrc

``` 

`gem install rmagick` installed `rmagick-5.3.0` successfully but which doesn't help.

I think the root cause is that somehow gem's installation is default for `rmagick-5.3.0`, and when I try to install 2.16.0, I saw exact same error message of bundle install. 

gem's version is 3.2.3
 

```
bundler -v 
Bundler version 2.4.22
```
`mdfind MagickWand.h` found nothing

  [1]: https://stackoverflow.com/questions/39699325/an-error-occurred-while-installing-rmagick-2-16-0-i-tried-all-option-provided

### Steps to Reproduce
`bundle install` or `gem install rmagick -v '2.16.0'`

### System Configuration

- ImageMagick version: 6.9.13-4
- RMagick version: looking for 2.16.0
- Ruby version: 2.6.6
- Environment (Operating system, version and so on): MacOS 14.2.1
- Additional information:

**Comment by Watson1978** [comment]
Please update rmagick

**Comment by yiningt-pp** [comment]
Hi @Watson1978 Thanks for reply. Could you be more specific? `gem install rmagick` installed rmagick-5.3.0  for me, how should I update and to what revision? I look for rmagick2.16.0 Thank you so much

**Comment by mockdeep** [comment]
@yiningt-pp you are trying to install RMagick version 2.16.0 which is no longer supported. Are you able to install RMagick version 5.3.0?

**Comment by yiningt-pp** [comment]
Hi @mockdeep thanks for reply. Understood, but the project and service are already 2.16.0 based. Is there any work around that I get 2.16.0 installed?  `RMagick version 5.3.0` does not help when I further build the project based on ImageMagick 6.9

**Comment by mockdeep** [comment]
@yiningt-pp it looks like you might have to install the ImageMagick headers as well based on the error message. But unfortunately we can't help you much if you're not running the most recent version. 2.16.0 is several years old and a lot of fixes have come in since then.

**Comment by sngsmz** [comment]
@yiningt-pp 
Downgrading the ImageMagick version to 6.9.12 fixed it.
Try this.

```
brew tap-new $USER/taps
brew tap homebrew/core --force
brew extract imagemagick@6 $USER/taps --version 6.9.12-98
brew install imagemagick@6.9.12-98
brew link --overwrite imagemagick@6.9.12-98
brew untap homebrew/core
brew untap $USER/taps
```
