### ISSUE TITLE
Installation fails on macOS with ImageMagick 7

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#1500]
### Steps to Reproduce

At first, remove `pkg-config command` with `brew uninstall pkg-config`.

Then, 

```
$ brew install imagemagick
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/manifests/7.1.1-29_1
Already downloaded: /Users/watson/Library/Caches/Homebrew/downloads/ef47da8f6631077750689eccbe84bdf860e9c56d0727910f6e4f351eafba770d--imagemagick-7.1.1-29_1.bottle_manifest.json
==> Fetching imagemagick
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:5270689f4064554efaaf086141377d2085f1ce9be42817a2b6d22a71d0626357
Already downloaded: /Users/watson/Library/Caches/Homebrew/downloads/f1ae0356920ddc70d3e1b5b8814f7476b4798e3c53a66e5bf4879dd5aca0af1d--imagemagick--7.1.1-29_1.arm64_sonoma.bottle.tar.gz
==> Pouring imagemagick--7.1.1-29_1.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/imagemagick/7.1.1-29_1: 809 files, 31.3MB
==> Running `brew cleanup imagemagick`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ gem install rmagick
Fetching pkg-config-1.5.6.gem
Successfully installed pkg-config-1.5.6
Building native extensions. This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    current directory: /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rmagick-5.4.4/ext/RMagick
/Users/watson/.rbenv/versions/3.3.0/bin/ruby extconf.rb
checking for brew... yes
checking for Ruby version >= 2.3.0... yes
Ignoring rmagick-5.4.4 because its extensions are not built. Try: gem pristine rmagick --version 5.4.4
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include=${opt-dir}/include
	--without-opt-include
	--with-opt-lib=${opt-dir}/lib
	--without-opt-lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/watson/.rbenv/versions/3.3.0/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:504:in `parse_pc': .pc doesn't exist: <MagickCore> (PackageConfig::NotFoundError)
	from /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:348:in `declaration'
	from /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:289:in `requires'
	from /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:545:in `block in required_packages'
	from /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:374:in `collect_requires'
	from /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:544:in `required_packages'
	from /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:452:in `collect_libs'
	from /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:310:in `libs'
	from /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:591:in `libs'
	from extconf.rb:344:in `assert_has_dev_libs!'
	from extconf.rb:321:in `assert_can_compile!'
	from extconf.rb:52:in `initialize'
	from extconf.rb:447:in `new'
	from extconf.rb:447:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/rmagick-5.4.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rmagick-5.4.4 for inspection.
Results logged to /Users/watson/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/rmagick-5.4.4/gem_make.out
```

### System Configuration

- ImageMagick version: 7.1.1-29_1
- RMagick version: 5.4.4
- Ruby version: 3.3.0
- Environment (Operating system, version and so on): macOS 14.4
- Additional information:

**Comment by Watson1978** [comment]
Success if pkg-config command is installed beforehand.

```
$ brew install pkg-config
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3
Already downloaded: /Users/watson/Library/Caches/Homebrew/downloads/ac691fc7ab8ecffba32a837e7197101d271474a3a84cfddcc30c9fd6763ab3c6--pkg-config-0.29.2_3.bottle_manifest.json
==> Fetching pkg-config
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/blobs/sha256:7b59abc0b5381065b1eab174217307af9324e0d02edf903171b29250ae58aeaf
Already downloaded: /Users/watson/Library/Caches/Homebrew/downloads/84ce7ed13999bc49b583c1b0bfd220d1bb0682ca2316d985b0f5f9e9c0a9084d--pkg-config--0.29.2_3.arm64_sonoma.bottle.tar.gz
==> Pouring pkg-config--0.29.2_3.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/pkg-config/0.29.2_3: 11 files, 676.7KB
==> Running `brew cleanup pkg-config`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ gem install rmagick
Building native extensions. This could take a while...
Successfully installed rmagick-5.4.4
1 gem installed
```

https://github.com/ruby-gnome/pkg-config/blob/38d7894bea55217f449d0524caa79c1dda39047d/lib/pkg-config.rb#L73-L87

It seems that the behavior of the `pkg-config  gem` changes depending on whether or not the `pkg-config command` is installed.

**Comment by Watson1978** [comment]
## Workaround
- Install `pkg-config command` beforehand with `brew install pkg-config`

or

- Use imagemagick6 with `brew install imagemagick@6`
