### ISSUE TITLE
rmagick fails to compile on AlmaLinux9

### ISSUE THREAD

**Issue by cbochs** [rmagick/rmagick#1659]
### Description

[Based on the README](https://github.com/rmagick/rmagick?tab=readme-ov-file#centos), the only dependencies for a CentOS-based OS are `gcc-c++` and `ImageMagick-devel`. When trying to install rmagick with these dependencies, it fails to compile on AlmaLinux9 with the following error:

<details>
<summary>Error Stdout</summary>

```
$ docker run --rm -it $(docker build -q .) gem install rmagick
...
Fetching rmagick-6.0.1.gem
Fetching pkg-config-1.5.6.gem
Successfully installed pkg-config-1.5.6
Building native extensions. This could take a while...
ERROR:  Error installing rmagick:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.1.0/gems/rmagick-6.0.1/ext/RMagick
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20240824-1-r2w9xd.rb extconf.rb
checking for brew... no
checking for pacman... no
checking for Ruby version >= 3.0.0... yes
checking for outdated ImageMagick version (<= 6.8.9)... no
checking for g++... yes

Warning: Found more than one ImageMagick installation. This could cause problems at runtime.
         /usr/bin/Magick-config reports version 6.9.13-14 Q16 is installed in /usr
         /bin/Magick-config reports version 6.9.13-14 Q16 is installed in /usr
Using 6.9.13-14 Q16 from /usr.

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-pkg-config
        --without-pkg-config
        --with-override-variables
        --without-override-variables
/usr/local/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
        from extconf.rb:126:in `configure_compile_options'
        from extconf.rb:48:in `initialize'
        from extconf.rb:438:in `new'
        from extconf.rb:438:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/3.1.0/extensions/aarch64-linux/3.1.0-static/rmagick-6.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/3.1.0/gems/rmagick-6.0.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/3.1.0/extensions/aarch64-linux/3.1.0-static/rmagick-6.0.1/gem_make.out
```

</details>

Inspecting the mkmf.log, the following errors stuck out to me:

```
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lgmp
```

It appears that `libz` and `libgmp` cannot be found. Inspecting the library locations and installed packages shows that `libz.so` and `libgmp.so` are not linked to their versioned counterparts:

```
$ docker run --rm -it $(docker build -q .) /bin/bash
[root@5195e91fee23 src]# dnf list installed | grep devel
ImageMagick-devel.aarch64                   6.9.13.14-1.el9               @epel
[root@5195e91fee23 src]# ls -la /usr/lib64/libz*
lrwxrwxrwx 1 root root     14 Sep 26  2023 /usr/lib64/libz.so.1 -> libz.so.1.2.11
-rwxr-xr-x 1 root root 135104 Sep 26  2023 /usr/lib64/libz.so.1.2.11
lrwxrwxrwx 1 root root     16 Apr  6  2022 /usr/lib64/libzstd.so.1 -> libzstd.so.1.5.1
-rwxr-xr-x 1 root root 730712 Apr  6  2022 /usr/lib64/libzstd.so.1.5.1
[root@5195e91fee23 src]# ls -la /usr/lib64/libgmp*
lrwxrwxrwx 1 root root     16 Oct 10  2023 /usr/lib64/libgmp.so.10 -> libgmp.so.10.4.0
-rwxr-xr-x 1 root root 532912 Oct 10  2023 /usr/lib64/libgmp.so.10.4.0
```

Adding the `zlib-devel` and `libgmp-devel` packages reconciles these missing links and installing rmagick (`gem install rmagick`) succeeds.

I'm not sure if this is a documentation issue for rmagick, or if the`ImageMagick-devel` package broke recently and should be installing `zlib-devel`/`libgmp-devel`, but I feel like this is an issue that should be addressed for future users who may hit the same problem.

### Steps to Reproduce

The following dockerfile builds ruby 3.1.2 for almalinux9 and installs `ImageMagick-devel` and `gcc-c++`:

```dockerfile
FROM almalinux:latest AS ruby

WORKDIR /src

RUN <<EOF
    dnf install \
        --nodocs \
        --setopt=fastmirror=1 \
        --assumeyes \
        --enablerepo=crb \
        autoconf \
        gcc \
        gmp-devel \
        libffi-devel \
        libyaml-devel \
        openssl-devel \
        zlib-devel

    dnf clean all
EOF

RUN <<EOF
    mkdir ruby
    curl -L https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.2.tar.gz | tar xz -C ruby --strip-components=1
EOF

WORKDIR /src/ruby
RUN ./autogen.sh

WORKDIR /src/build
RUN /src/ruby/configure --prefix=/usr/local && make && make install

FROM almalinux:latest

WORKDIR /src

RUN <<EOF
    dnf install \
        --nodocs \
        --setopt=fastmirror=1 \
        --assumeyes \
        epel-release

    dnf install \
        --nodocs \
        --setopt=fastmirror=1 \
        --assumeyes \
        --enablerepo=epel \
        ImageMagick-devel \
        gcc-c++

    dnf clean all
EOF

COPY --from=ruby /usr/local /usr/local
```

Run with

```
docker run --rm -it $(docker build -q .) gem install rmagick
```

### System Configuration

- ImageMagick version: 6.9.13.14-1.el9
- RMagick version: N/A
- Ruby version: 3.1.2
- Environment (Operating system, version and so on): AlmaLinux 9 (Docker)
- Additional information:

**Comment by Watson1978** [comment]
You will get the same error when installing a gem made in another C language.

```
# gem i oj
Fetching oj-3.16.5.gem
Building native extensions. This could take a while...
ERROR:  Error installing oj:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.1.0/gems/oj-3.16.5/ext/oj
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20240824-53-n19mxy.rb extconf.rb
>>>>> Creating Makefile for ruby version 3.1.2 on x86_64-linux <<<<<
checking for rb_gc_mark_movable()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-oj-dir
        --without-oj-dir
        --with-oj-include
        --without-oj-include=${oj-dir}/include
        --with-oj-lib
        --without-oj-lib=${oj-dir}/lib
/usr/local/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:830:in `try_func'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:1119:in `block in have_func'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:1007:in `block in checking_for'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:362:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
        from /usr/local/lib/ruby/3.1.0/mkmf.rb:1118:in `have_func'
        from extconf.rb:29:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0-static/oj-3.16.5/mkmf.log

extconf failed, exit code 1
```

The libraries used to build Ruby are also required at runtime.
So, you should install libraries into your runtime image.

* libffi-devel
* libyaml-devel
* openssl-devel
* zlib-devel
