### ISSUE TITLE
libMagickCore.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by nicksnels** [rmagick/rmagick#221]
Hi,

I'm running a Centos 6 server with Rails 3.2.18, rmagick 2.15.3 and ImageMagick 6.7.2-7 2015-07-23 Q16. When I restart my server or run rails r -e production I get the following error:

```
/var/www/jobs/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require': libMagickCore.so.2: cannot open shared object file: No such file or directory - /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/rmagick-2.15.3/lib/RMagick2.so (LoadError)
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `block in require'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/rmagick-2.15.3/lib/rmagick_internal.rb:12:in `<top (required)>'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `block in require'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/rmagick-2.15.3/lib/rmagick.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
        from /usr/local/rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
        from /usr/local/rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
        from /usr/local/rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
        from /usr/local/rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
        from /var/www/jobs/config/application.rb:8:in `<top (required)>'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands/runner.rb:43:in `require'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands/runner.rb:43:in `<top (required)>'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands.rb:64:in `require'
        from /var/www/jobs/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands.rb:64:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

I have already done export LD_LIBRARY_PATH=/usr/local/lib and I have also added it to .bashrc . Any ideas how I can solve this? Thank you.

**Comment by vassilevsky** [comment]
Could you update it to the latest version 2.15.4 that I released recently and report if it works?

**Comment by nicksnels** [comment]
I updated to 2.15.4 and it works again. Thank you!

Only warning I get when I run rails r is:
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
