### ISSUE TITLE
LoadError: 127: The specified procedure could not be found. - C:/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/rmagick-2.15.4/RMagick2.so (LoadError)

### ISSUE THREAD

**Issue by 4lex-gs** [rmagick/rmagick#253]
Hi,
I encountered this error.
I tried many methods to solve it.
But, I can't solve it.

Windows 8.1 with Bing [Version 6.3.9600]
Ruby 2.1.8 p440
Ruby Gems Version 2.2.5
ImageMagick-6.9.3-6-Q8-x86-dll 
RMagick 2.15.4

```
require "rmagick"
```

```
C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require': 127: The specified procedure could not be found. - C:/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/rmagick-2.15.4/RMagick2.so (LoadError)
  from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
  from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
  from C:/Ruby21/lib/ruby/gems/2.1.0/gems/rmagick-2.15.4/lib/rmagick_internal.rb:12:in `<top (required)>'
  from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from C:/Ruby21/lib/ruby/gems/2.1.0/gems/rmagick-2.15.4/lib/rmagick.rb:1:in `<top (required)>'
  from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
  from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
  from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
  from C:/Users/Souta/Desktop/ATRUSS-win32-ia32/resources/lib/temes/image.rb:3:in `<encoded>'
  from C:/Users/Souta/Desktop/ATRUSS-win32-ia32/resources/lib/temes/image.rb:2:in `<top (required)>'
  from C:/Users/Souta/Desktop/ATRUSS-win32-ia32/resources/lib/temes.rb:58:in `require_relative'
  from C:/Users/Souta/Desktop/ATRUSS-win32-ia32/resources/lib/temes.rb:58:in `<encoded>'
  from C:/Users/Souta/Desktop/ATRUSS-win32-ia32/resources/lib/temes.rb:2:in `<top (required)>'
  from C:/Users/Souta/Desktop/ATRUSS-win32-ia32/resources/lib/temes_app.rb:21:in `require_relative'
  from C:/Users/Souta/Desktop/ATRUSS-win32-ia32/resources/lib/temes_app.rb:21:in `<encoded>'
  from C:/Users/Souta/Desktop/ATRUSS-win32-ia32/resources/lib/temes_app.rb:2:in `<main>'
```

```
irb(main):001:0> require "rmagick"
LoadError: 127: The specified procedure could not be found. - C:/Ruby21/lib/ruby/
gems/2.1.0/extensions/x86-mingw32/2.1.0/rmagick-2.15.4/RMagick2.so
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in
 `require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in
 `rescue in require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in
 `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/rmagick-2.15.4/lib/rmagick_inter
nal.rb:12:in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/rmagick-2.15.4/lib/rmagick.rb:1:
in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in
 `require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in
 `rescue in require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in
 `require'
        from (irb):1
        from C:/Ruby21/bin/irb:11:in `<main>'
```

**Comment by rsibanez89** [comment]
Follow this tutorial https://medium.com/ruby-on-rails-web-application-development/install-rmagick-gem-on-windows-7-8-10-imagemagick-6-9-4-q16-hdri-5492c3fef202

**Comment by Watson1978** [comment]
I think this issue should be solved by https://github.com/rmagick/rmagick/pull/315.
