### ISSUE TITLE
Symbol not found: _AdaptiveBlurImage (LoadError)

### ISSUE THREAD

**Issue by arturictus** [rmagick/rmagick#287]
Hi,
I can not load the Ruby environment because rmagick is not finding dependencies of imagemagick.
I've been trying to install different versions of imagemagick with no luck.
If someone had the same problem and found a fix. Please help me!!

My system:
MacOs: El capitan 10.11.6
rmagick: 2.16.0
imagemagick: 7.0.7-21

installed with homebrew (`brew install imagemagick`)

ERROR:

```
/Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/rmagick-2.16.0/lib/rmagick_internal.rb:12:in `require': dlopen(/Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/rmagick-2.16.0/RMagick2.bundle, 9): Symbol not found: _AdaptiveBlurImage (LoadError)
  Referenced from: /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/rmagick-2.16.0/RMagick2.bundle
  Expected in: /usr/local/lib/libMagickWand-6.Q16.2.dylib
 in /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/rmagick-2.16.0/RMagick2.bundle - /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/rmagick-2.16.0/RMagick2.bundle
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/rmagick-2.16.0/lib/rmagick_internal.rb:12:in `<top (required)>'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/rmagick-2.16.0/lib/rmagick.rb:1:in `require'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/rmagick-2.16.0/lib/rmagick.rb:1:in `<top (required)>'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/worldize-0.0.1/lib/worldize.rb:2:in `require'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/worldize-0.0.1/lib/worldize.rb:2:in `<top (required)>'
	from /Users/arturpanach/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
	from /Users/arturpanach/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/arturpanach/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	from /Users/arturpanach/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	from /Users/arturpanach/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	from /Users/arturpanach/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	from /Users/arturpanach/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	from /Volumes/external/projects/path/config/application.rb:11:in `<top (required)>'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Volumes/external/projects/path/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

I really appreciate help

**Comment by arturictus** [comment]
I've tried:

https://stackoverflow.com/questions/15162496/rmagick-preventing-rails-server-from-working
```
brew uninstall imagemagick
gem uninstall rmagick
gem install json # (not sure this step is needed)
brew install libmagick9-dev
bundle install
```

**Comment by mooninite** [comment]
Rmagick does not support ImageMagick 7. Please see issue 265.

**Comment by arturictus** [comment]
thanks @mooninite

**Comment by mockdeep** [comment]
Closing this. We're tracking support for ImageMagick 7 in https://github.com/rmagick/rmagick/issues/256.

**Comment by nonuabi** [comment]
> I've tried:
> 
> https://stackoverflow.com/questions/15162496/rmagick-preventing-rails-server-from-working
> 
> ```
> brew uninstall imagemagick
> gem uninstall rmagick
> gem install json # (not sure this step is needed)
> brew install libmagick9-dev
> bundle install
> ```

this solution is not working on Mac m1(monterey)

**Comment by baranyeni** [comment]
> nonuabi

Did you had a change to fix it somehow? I am also on M1 having same issue no solution..

**Comment by h0jeZvgoxFepBQ2C** [comment]
I have a quite similar error message after upgrading OSX to Ventura:

```
/Users/user/.rvm/gems/ruby-2.7.7/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require': dlopen(/Users/user/.rvm/gems/ruby-2.7.7/gems/rmagick-4.2.4/lib/RMagick2.bundle, 0x0009): symbol not found in flat namespace '_AcquireDrawInfo' - /Users/user/.rvm/gems/ruby-2.7.7/gems/rmagick-4.2.4/lib/RMagick2.bundle (LoadError)
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `block in require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:299:in `load_dependency'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/rmagick-4.2.4/lib/rmagick_internal.rb:23:in `<main>'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `block in require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:299:in `load_dependency'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/rmagick-4.2.4/lib/rmagick.rb:1:in `<main>'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
  from /Users/user/coding/flave-admin/config/application.rb:13:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
  from /Users/user/.rvm/gems/ruby-2.7.7/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
  from /Users/user/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  from /Users/user/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
```

And the mentioned solution worked last time, but not now on Ventura :(

**Comment by tokuchi0823** [comment]
I have a quite similar error message after upgrading OSX to Montery, too:
```
my-useri@myname-name-Pro salon_management_system % rails s          
Traceback (most recent call last):
	49: from bin/rails:3:in `<main>'
	48: from bin/rails:3:in `load'
	47: from /Users/my-useri/salon_management_system/bin/spring:15:in `<top (required)>'
	46: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	45: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	44: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/binstub.rb:11:in `<top (required)>'
	43: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/binstub.rb:11:in `load'
	42: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/bin/spring:49:in `<top (required)>'
	41: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/client.rb:30:in `run'
	40: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/client/command.rb:7:in `call'
	39: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/client/rails.rb:28:in `call'
	38: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/client/rails.rb:28:in `load'
	37: from /Users/my-useri/salon_management_system/bin/rails:9:in `<top (required)>'
	36: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	35: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	34: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/commands.rb:18:in `<main>'
	33: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/command.rb:46:in `invoke'
	32: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/command/base.rb:69:in `perform'
	31: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	30: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	29: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	28: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	27: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	26: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	25: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
	24: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	23: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
	22: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	21: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	20: from /Users/my-useri/salon_management_system/config/application.rb:7:in `<main>'
	19: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler.rb:187:in `require'
	18: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:44:in `require'
	17: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:44:in `each'
	16: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:55:in `block in require'
	15: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:55:in `each'
	14: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	13: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	12: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	11: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rmagick-5.3.0/lib/rmagick.rb:3:in `<main>'
	10: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
	 9: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	 8: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
	 7: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 6: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 5: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rmagick-5.3.0/lib/rmagick_internal.rb:25:in `<main>'
	 4: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
	 3: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	 2: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
	 1: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': dlopen(/Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rmagick-5.3.0/lib/RMagick2.bundle, 0x0009): symbol not found in flat namespace (_AcquireDrawInfo) - /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rmagick-5.3.0/lib/RMagick2.bundle (LoadError)
```

**Comment by tokuchi0823** [comment]
However, The latest version, I have a quite similar error message on Montery:
```
my-useri@myname-name-Pro system % rails s          
Traceback (most recent call last):
	49: from bin/rails:3:in `<main>'
	48: from bin/rails:3:in `load'
	47: from /Users/my-useri/system/bin/spring:15:in `<top (required)>'
	46: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	45: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	44: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/binstub.rb:11:in `<top (required)>'
	43: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/binstub.rb:11:in `load'
	42: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/bin/spring:49:in `<top (required)>'
	41: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/client.rb:30:in `run'
	40: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/client/command.rb:7:in `call'
	39: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/client/rails.rb:28:in `call'
	38: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/spring-4.1.3/lib/spring/client/rails.rb:28:in `load'
	37: from /Users/my-useri/system/bin/rails:9:in `<top (required)>'
	36: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	35: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	34: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/commands.rb:18:in `<main>'
	33: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/command.rb:46:in `invoke'
	32: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/command/base.rb:69:in `perform'
	31: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	30: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	29: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	28: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	27: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	26: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	25: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
	24: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	23: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
	22: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	21: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	20: from /Users/my-useri/system/config/application.rb:7:in `<main>'
	19: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler.rb:187:in `require'
	18: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:44:in `require'
	17: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:44:in `each'
	16: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:55:in `block in require'
	15: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:55:in `each'
	14: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.19/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	13: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	12: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	11: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rmagick-5.3.0/lib/rmagick.rb:3:in `<main>'
	10: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
	 9: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	 8: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
	 7: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 6: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 5: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rmagick-5.3.0/lib/rmagick_internal.rb:25:in `<main>'
	 4: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
	 3: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	 2: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
	 1: from /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': dlopen(/Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rmagick-5.3.0/lib/RMagick2.bundle, 0x0009): symbol not found in flat namespace (_AcquireDrawInfo) - /Users/my-useri/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/rmagick-5.3.0/lib/RMagick2.bundle (LoadError)

```
