### ISSUE TITLE
Can't install with ImageMagick.x86_64-6.7.8.9-15.21.amzn1

### ISSUE THREAD

**Issue by dpresling** [rmagick/rmagick#295]
Amazon have updated their repo for Amazon Linux to use 

`ImageMagick.x86_64 0:6.7.8.9-15.21.amzn1`
and
`ImageMagick-devel.x86_64 0:6.7.8.9-15.21.amzn1`

now rmagick 2.16.0 won't build. There doesn't appear to be a rollback option in the repo. 

output of `gem install rmagick` 

```
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20180507-2741-3ioira.rb extconf.rb
checking for gcc... yes
checking for Magick-config... yes

Warning: Found a partial ImageMagick installation. Your operating system likely has some built-in ImageMagick libraries but not all of ImageMagick. This will most likely cause problems at both compile and runtime.
Found partial installation at: /usr
checking for outdated ImageMagick version (<= 6.4.9)... no
checking for presence of MagickWand API (ImageMagick version >= 6.9.0)... no
checking for Ruby version >= 1.8.5... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.2
/usr/share/ruby/2.2/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/2.2/mkmf.rb:587:in `try_cpp'
	from /usr/share/ruby/2.2/mkmf.rb:1060:in `block in have_header'
	from /usr/share/ruby/2.2/mkmf.rb:911:in `block in checking_for'
	from /usr/share/ruby/2.2/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/share/ruby/2.2/mkmf.rb:321:in `open'
	from /usr/share/ruby/2.2/mkmf.rb:351:in `block in postpone'
	from /usr/share/ruby/2.2/mkmf.rb:321:in `open'
	from /usr/share/ruby/2.2/mkmf.rb:347:in `postpone'
	from /usr/share/ruby/2.2/mkmf.rb:910:in `checking_for'
	from /usr/share/ruby/2.2/mkmf.rb:1059:in `have_header'
	from extconf.rb:39:in `configure_headers'
	from extconf.rb:18:in `initialize'
	from extconf.rb:548:in `new'
	from extconf.rb:548:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in ~/.gem/ruby/2.2/gems/rmagick-2.16.0 for inspection.
Results logged to ~/.gem/ruby/2.2/extensions/x86_64-linux/2.2/rmagick-2.16.0/gem_make.out
```

Does anybody have any suggestion for how to fix this / be able to install rmagick again?

**Comment by mockdeep** [comment]
Hi @dpresling, thanks for reporting. We've deprecated support for ImageMagick 6.7 as of RMagick 3.0.0. Please upgrade if you can.
