### ISSUE TITLE
Converting JPEG from RGB to CMYK results in segfault

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#36]
<a href="https://github.com/meanphil"><img src="https://avatars.githubusercontent.com/u/7361?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meanphil](https://github.com/meanphil)**
_Tuesday Jul 10, 2012 at 23:27 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/55_

---

Trying to save any image as a CMYK Jpeg will result in a crash. If you change CMYK to any other colorspace such as RGB, CMY, or Gray it writes the image OK.

My test script is as follows:

``` ruby
require 'rubygems'; require 'RMagick'

i = Magick::Image.read('test.jpg').first 
i.write("cmyk.jpg") do |ii|
    ii.format = 'JPEG'
    ii.colorspace = Magick::CMYKColorspace
end
```

```
$ ruby test.rb 
test.rb:4: [BUG] Segmentation fault
```

gdb says the segfault is in ImageMagick here:

```
0x0000000803642ef7 in WriteJPEGImage (image_info=0x80386f000, image=0x803859000) at coders/jpeg.c:2604
2604                  *q++=(JSAMPLE) (ScaleQuantumToChar((Quantum) (QuantumRange-
```

However the following command line works fine, so it must be something that RMagick is (not?) doing:

```
convert test.jpg -colorspace CMYK cmyk.jpg
```

Environment is Ruby 1.9.3-p194, ImageMagick 6.7.7-7, RMagick 2.13.1, FreeBSD 8.2, gcc 4.2.1

**Comment by Watson1978** [comment]
This issue still reproduce with Ruby 2.3 and RMagick 3.0.0.

```
$ ruby -v thumbnail.rb
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin18]
thumbnail.rb:4: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin18]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0009 e:000008 CFUNC  :write
c:0002 p:0040 s:0005 E:0003d8 EVAL   thumbnail.rb:4 [FINISH]
c:0001 p:0000 s:0002 E:001b40 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
thumbnail.rb:4:in `<main>'
thumbnail.rb:4:in `write'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000000 rbx: 0x00007ff6808c6a00 rcx: 0x0000000000000000
 rdx: 0x0000000000000080 rdi: 0x00007ff681811200 rsi: 0x0000000000000000
 rbp: 0x00007ffee8840e50 rsp: 0x00007ffee88409a0  r8: 0x0000000000000000
  r9: 0x00007ff681814478 r10: 0x00007ff67e72fe30 r11: 0x00000001079cc585
 r12: 0x00007ff681811200 r13: 0x0000000107f87000 r14: 0x0000000000000000
 r15: 0x00007ff681814478 rip: 0x0000000107c81394 rfl: 0x0000000000010202

-- C level backtrace information -------------------------------------------
0   ruby                                0x0000000107579a39 rb_vm_bugreport + 377
1   ruby                                0x00000001074086cf rb_bug_context + 447
2   ruby                                0x00000001074e7aa4 sigsegv + 68
3   libsystem_platform.dylib            0x00007fff6c51cb3d _sigtramp + 29
4   jpeg.so                             0x0000000107c81394 WriteJPEGImage + 7546
5   libMagickCore-6.Q16.6.dylib         0x00000001079f1bf3 WriteImage + 1819
6   RMagick2.bundle                     0x0000000107863fd2 Image_write + 290
7   ruby                                0x000000010756f5ab vm_call_cfunc + 299
8   ruby                                0x0000000107558a3e vm_exec_core + 10094
9   ruby                                0x0000000107569a55 vm_exec + 117
10  ruby                                0x0000000107411496 ruby_exec_internal + 150
11  ruby                                0x00000001074113a8 ruby_run_node + 56
12  ruby                                0x00000001073bd5df main + 79

-- Other runtime information -----------------------------------------------

* Loaded script: thumbnail.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/x86_64-darwin18/enc/encdb.bundle
    5 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/x86_64-darwin18/enc/trans/transdb.bundle
    6 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/unicode_normalize.rb
    7 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/x86_64-darwin18/rbconfig.rb
    8 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/compatibility.rb
    9 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/defaults.rb
   10 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/deprecate.rb
   11 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/errors.rb
   12 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/version.rb
   13 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/requirement.rb
   14 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/platform.rb
   15 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/basic_specification.rb
   16 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/stub_specification.rb
   17 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/util/list.rb
   18 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/x86_64-darwin18/stringio.bundle
   19 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/rfc2396_parser.rb
   20 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/rfc3986_parser.rb
   21 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/common.rb
   22 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/generic.rb
   23 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/ftp.rb
   24 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/http.rb
   25 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/https.rb
   26 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/ldap.rb
   27 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/ldaps.rb
   28 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri/mailto.rb
   29 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/uri.rb
   30 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/specification.rb
   31 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/exceptions.rb
   32 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/dependency.rb
   33 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb
   34 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/monitor.rb
   35 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb
   36 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems.rb
   37 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/rubygems/path_support.rb
   38 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/version.rb
   39 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb
   40 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/levenshtein.rb
   41 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/jaro_winkler.rb
   42 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkable.rb
   43 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/delegate.rb
   44 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   45 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   46 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   47 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   48 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/null_checker.rb
   49 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/formatter.rb
   50 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean.rb
   51 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/English.rb
   52 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/2.3.0/observer.rb
   53 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rmagick-3.0.0/lib/RMagick2.bundle
   54 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rmagick-3.0.0/lib/rmagick_internal.rb
   55 /Users/s-fujita/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rmagick-3.0.0/lib/rmagick.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[1]    23347 abort      ruby -v thumbnail.rb
```
