### ISSUE TITLE
libMagickCore-6.Q16.so.2 error on Ubuntu 18.04

### ISSUE THREAD

**Issue by onnudilol** [rmagick/rmagick#473]
It seems like the `libMagickCore` package in Ubuntu 18.04 ships with `libMagickCore-6.Q16.so.3`.

https://packages.ubuntu.com/bionic/amd64/libmagickcore-6.q16-3/filelist

Here's the traceback

```
I, [2019-03-22T14:22:00.603710 #21968]  INFO -- : Refreshing Gem list
LoadError: libMagickCore-6.Q16.so.2: cannot open shared object file: No such file or directory - /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/rmagick-3.0.0/lib/RMagick2.so
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/rmagick-3.0.0/lib/rmagick_internal.rb:22:in `<top (required)>'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/rmagick-3.0.0/lib/rmagick.rb:1:in `<top (required)>'
  /home/mikhailn/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
  /home/mikhailn/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  /home/mikhailn/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
  /home/mikhailn/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
  /home/mikhailn/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
  /home/mikhailn/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
  /home/mikhailn/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
  /opt/mikhailn/releases/20190322142132/qbhouse/config/application.rb:7:in `<top (required)>'
  /opt/mikhailn/releases/20190322142132/qbhouse/config/environment.rb:2:in `require'
  /opt/mikhailn/releases/20190322142132/qbhouse/config/environment.rb:2:in `<top (required)>'
  config.ru:2:in `require'
  config.ru:2:in `block in <main>'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `instance_eval'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `eval'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `block in builder'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:795:in `build_app!'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:139:in `start'
  /opt/mikhailn/shared/bundle/qbhouse/ruby/2.4.0/gems/unicorn-5.4.1/bin/unicorn:126:in `<top (required)>'
```

**Comment by Watson1978** [comment]
At the moment, I think it's difficult to detect changes in the ImageMagick installation paths.

So, please reinstall RMagick when upgrade ImageMagick. I think you can solve the issue easily.
